 apiVersion: v1
 kind: Service
 metadata:
   name: micro-api
   namespace: default
   labels:
     micro: runtime
     name: api
     version: latest
 spec:
   ports:
   - name: http
     port: 8080
     targetPort: 8080
   selector:
     name: micro-api
     micro: runtime
     version: latest
